# This is a basic workflow to help you get started with Actions

name: GitHub Pages Build & Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci
     
      - name: Build GitHub Pages Content
        run: npm run build && npm run build.ssg && node server/entry.static.js

      - name: Deploy GitHub Pages
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          # Path of the directory containing the static assets.
          path: dist/
